### ISSUE TITLE
Announce this github repo on the HOT email list?

### ISSUE THREAD

**Issue by bgirardot** [hotosm/Hewlett-Foundation#22]
Considering the push back we are getting (and giving ;) about opening up the processes of HOT US Inc., this is a great example of opening up the process.

Can we announce this repo on the HOT Email list?

**Comment by mataharimhairi** [comment]
Great idea! I have just sent an e-mail announcing this GitHub repository, so that everyone can be kept up to date on what is happening with the Hewlett Foundation grant and related projects.
